### PR TITLE
Initial commit of all files and folders for the Convert Page.

### PR DESCRIPTION
**Pull request by DARQ-Envoy**

### CODE REVIEW

**Comment by DARQ-Envoy** [comment]
All code files for the converter Page

**Comment by DARQ-Envoy** [comment]
It contains the " converting " file and " Success " Modals as well as a bootstrap off canvas with about 3 breakpoints.

**Comment by coded1guy** [comment]
I don't think we decided to use bootstrap, though its not much of a problem, but try to minify the files (remove unnecessary styles in the files)

**Comment by megalous-lab** [comment]
This is great!
But we need some corrections..

1. We didn't agree on using bootstrap. (I'll talk with other devs on slack to know if we can all go with it)
2. You're not supposed to name the page with index. The page should be named convert_files.html, convert_files.css and so on.
3. Let me know on slack if you can bootstrap other pages too...

**Comment by coded1guy** [comment]
> 

I don't think we should use bootstrap though, it has some default styles that become hard to restyle because most times they use the "!important" CSS property, this is also not a big project, so why increase the load speed of the site when we could have a simple CSS style it.

**Comment by DARQ-Envoy** [comment]
Worked on the Landing Page and reduced the files to only the necessary

**Pull request merged**
